[New] added test cases for record actions add incident fields
primeroIMS/primero pull request #216
Opened 2023-07-10 11:27 UTC by Srinivas9933

Added test cases for record actions add incident fields

2024-03-05 14:36 UTC, aespinoza-quoin requested changes

2024-03-05 14:36 UTC, aespinoza-quoin commented on app/javascript/components/record-actions/add-incident/fields/component.spec.js
> +    expect(screen.getByRole("textbox")).toBeInTheDocument();
Use testid instead of role.

2024-05-14 18:15 UTC, jtoliver-quoin commented on app/javascript/components/record-actions/add-incident/fields/component.spec.js
>    it("renders component with valid props", () => {
Remove

2024-05-15 12:49 UTC, Srinivas9933 commented on app/javascript/components/record-actions/add-incident/fields/component.spec.js
>    it("renders component with valid props", () => {
Done

2024-05-20 14:01 UTC, merged