[New] Trigyn testcases record actions
primeroIMS/primero pull request #234
Opened 2023-07-25 10:33 UTC by Srinivas9933

[New] Added test cases for record actions.

2024-02-13 00:43 UTC, aespinoza-quoin requested changes

2024-02-13 00:43 UTC, aespinoza-quoin commented on app/javascript/components/record-actions/container.spec.js
> +  //   let component;
remove this comment

2024-02-13 00:43 UTC, aespinoza-quoin commented on app/javascript/components/record-actions/container.spec.js
> +      expect(screen.queryAllByRole("dialog")).toHaveLength(1);
Verify if it is a Transfer

2024-02-13 00:43 UTC, aespinoza-quoin commented on app/javascript/components/record-actions/container.spec.js
> +      expect(screen.queryAllByRole("dialog")).toHaveLength(1);
Verify if it is a RequestApproval

2024-04-02 07:16 UTC, Srinivas9933 commented on app/javascript/components/record-actions/container.spec.js
> +  //   let component;
Done

2024-04-02 07:16 UTC, Srinivas9933 commented on app/javascript/components/record-actions/container.spec.js
> +      expect(screen.queryAllByRole("dialog")).toHaveLength(1);
Done

2024-04-02 07:16 UTC, Srinivas9933 commented on app/javascript/components/record-actions/container.spec.js
> +      expect(screen.queryAllByRole("dialog")).toHaveLength(1);
Done

2024-06-01 04:29 UTC, merged