Send email alerts on certain field changes.
primeroIMS/primero pull request #296
Opened 2023-08-28 14:00 UTC by awensaunders

Sometimes there is a need to send emails when certain fields are changed and a record is assigned to multiple users (as in a referral). This PR is an implementation of that.

2023-09-27 20:51 UTC, aespinoza-quoin commented on app/jobs/alert_notify_job.rb
> +    users.each do |user|
If the job failed for one user, should continue with the next one? can you make sure that this is happening?

2023-09-27 20:51 UTC, aespinoza-quoin commented on app/models/concerns/alertable.rb
> +    case conf_record.alert_strategy
make sure you run rubocop for all the files added/modified
please leave a comment that this is partially implemented.

2023-09-27 20:51 UTC, aespinoza-quoin commented on app/models/concerns/alertable.rb
> +class AlertConfigEntry
why not a new file?

2023-09-27 20:51 UTC, aespinoza-quoin commented on app/services/alert_notification_service.rb
> +    # We may want to add some checks here in the future.
TODO?

2023-09-27 20:51 UTC, aespinoza-quoin commented on app/mailers/record_action_mailer.rb
> +    @user = @alert_notification.user
@user, @locale_email and @record are not need it in the view you can use @alert_notification

2023-09-27 20:51 UTC, aespinoza-quoin commented on app/views/record_action_mailer/alert_notify.html.erb
> +<html lang="<%= @user.locale || I18n.locale %>">
@alert_notification.locale

2023-09-27 20:51 UTC, aespinoza-quoin commented on app/views/record_action_mailer/alert_notify.html.erb
> +          locale: @locale_email
@alert_notification.locale

2023-09-27 20:51 UTC, aespinoza-quoin commented on app/views/record_action_mailer/alert_notify.text.erb
> +    locale: @locale_email
@alert_notification.locale

2023-09-27 20:52 UTC, aespinoza-quoin commented
Please make sure to run rubocop.

2023-09-28 13:46 UTC, awensaunders commented
> Please make sure to run rubocop.

Is there some particular way you’re invoking rubocop? I’m not seeing any rubocop warnings on these changed files.

2023-10-16 16:28 UTC, awensaunders commented
I've added the ability to dismiss alerts by adding a new API route and some frontend stuff. I'm not super familiar with the frontend of primero, so I would appreciate any comments.

See video of what the frontend looks like below:
https://github.com/primeroIMS/primero/assets/3837160/31404b5e-2e25-45a8-9f18-1d3a52d3a778

2023-10-16 21:05 UTC, jtoliver-quoin commented on app/javascript/components/records/action-creators.js
> +  // TODO this should be a const interpolated here not a literal
Remove todo, this should be fine as is

2023-10-16 21:05 UTC, jtoliver-quoin commented on app/javascript/components/internal-alert/component.jsx
> +  const renderDismissButton = handler => {
Make these renderItem and renderDismissButton components in another file under components/internal-alert/components

2023-10-24 20:48 UTC, pnabutovsky requested changes

2023-10-24 20:48 UTC, pnabutovsky commented on app/controllers/api/v2/alerts_controller.rb
> +    authorize! :update, @record
Can you remove the :update permission check? The alert dismissal shows up on the show page, which means that someone without edit permissions but with remove alert permissions will be able to see the button. And this is a reasonable usecase to support: managers will likely want to dismiss alerts.

2023-10-25 20:53 UTC, merged