Develop verify for mrm
primeroIMS/primero pull request #324
Opened 2023-09-07 13:55 UTC by ajit3190

2023-09-11 15:48 UTC, pnabutovsky requested changes
When creating new application strings under config/locales only modify the English files. Please do not edit the other language files: they are maintained with Transifex. Primero automatically provides the English string (or sometimes a language fallback chain) if a translation is missing.

2023-09-19 15:29 UTC, jtoliver-quoin requested changes

2023-09-19 15:29 UTC, jtoliver-quoin commented on app/javascript/components/record-form/form/subforms/styles.css
> +  color: white;
Use `var(--c-white)` instead

2023-09-19 15:29 UTC, jtoliver-quoin commented on app/javascript/components/record-form/form/subforms/styles.css
> +  font-size: 13px;
use `var(--fs-13)`

2023-09-19 15:29 UTC, jtoliver-quoin commented on app/javascript/components/record-form/form/subforms/subform-fields/components/violation-item/component.jsx
> +import { Button } from "@material-ui/core";
Run`npm run lint` and `npm run test` and fix any lint issues or test

2023-09-19 15:29 UTC, jtoliver-quoin commented on app/javascript/components/record-form/form/subforms/subform-fields/components/violation-item/component.jsx
> +  const [selectedIndex, setSelectedIndex] = useState(null);
group useState variables together

2023-09-19 15:29 UTC, jtoliver-quoin commented on app/javascript/components/record-form/form/subforms/subform-fields/components/violation-item/component.jsx
> +  const handleOpenVerifyModal = (index,event) => {    //  To open verify dialog confirmation popup
Add a newline above

2023-09-19 15:29 UTC, jtoliver-quoin commented on app/javascript/components/record-form/form/subforms/subform-fields/components/violation-item/component.jsx
> +  const handleOk = () => {    //  To update the verify status to Verified
Add a new line above

2023-09-19 15:29 UTC, jtoliver-quoin commented on app/javascript/components/record-form/form/subforms/subform-fields/components/violation-item/component.jsx
> +  const {
Add a newline above

2023-09-19 15:29 UTC, jtoliver-quoin commented on app/javascript/components/record-form/form/subforms/subform-fields/components/violation-item/styles.css
> +  outline: 4px solid rgba(31, 176, 214, 0.4);
The color used here should be added to our root css vars or use one of the existing css vars

2023-09-19 15:29 UTC, jtoliver-quoin commented on app/javascript/components/record-form/form/subforms/subform-fields/components/violation-item/styles.css
> +  outline: 4px solid rgba(31, 176, 214, 0.4);
This color is a little odd. Could you attach a screenshot of this?

2024-03-25 18:39 UTC, merged