[New] Added test cases for pages admin roles list
primeroIMS/primero pull request #338
Opened 2023-09-14 05:29 UTC by Srinivas9933

Added test cases for pages admin roles list component.

- container.spec.js

2024-02-07 23:11 UTC, aespinoza-quoin requested changes

2024-02-07 23:11 UTC, aespinoza-quoin commented on app/javascript/components/pages/admin/roles-list/container.spec.js
> +  it("should trigger a sort action when a header is clicked", () => {
this test is duplicated. L47

2024-04-04 11:44 UTC, Srinivas9933 commented on app/javascript/components/pages/admin/roles-list/container.spec.js
> +        expect(screen.getAllByTestId('action-button')).toHaveLength(2);
Done

2024-04-04 11:44 UTC, Srinivas9933 commented on app/javascript/components/action-button/component.jsx
> +    data-testid="action-button"
Done

2024-05-14 18:26 UTC, merged