[New] Added test cases pages dashboard components overdue tasks
primeroIMS/primero pull request #339
Opened 2023-09-14 06:23 UTC by Srinivas9933

Added test cases pages dashboard components overdue tasks component.

- component.spec.js

2024-02-09 18:48 UTC, dhernandez-quoin requested changes

2024-03-28 12:07 UTC, Srinivas9933 commented on app/javascript/components/pages/dashboard/components/overdue-tasks/component.spec.js
> +    expect(screen.getAllByRole('row')).toHaveLength(2);
Done

2024-03-28 12:07 UTC, Srinivas9933 commented on app/javascript/components/pages/dashboard/components/overdue-tasks/component.spec.js
> +      expect(screen.getByTestId('option-box')).toBeInTheDocument();
Done

2024-05-24 14:15 UTC, dhernandez-quoin approved these changes

2024-05-24 14:15 UTC, merged